In [3]:
import numpy as np
import pandas as pd
"""
@Author: Gyanendra
@Date: 19/01/2021 
@Last Modified by: Gyanendra
@Last Modified time: 19/01/2021 
@Title : Pandas Python Problems
"""

'\n@Author: Gyanendra\n@Date: 19/01/2021 \n@Last Modified by: Gyanendra\n@Last Modified time: 19/01/2021 \n@Title : Pandas Python Problems\n'

In [4]:
# 1-Python program to create and display a one-dimensional array-like object containing
#  an array of data using Pandas module.
"""
Description:
    Function is Used create and display a one-dimensional array-like object containing
    an array of data using Pandas module
Parameter:
    Sample Array
Return:
    None
"""
sample_array = pd.Series([1,2,3,4,5])  #This method computes the dot product between the Series and another one, or the Series and each columns of a DataFrame,
                                        # or the Series and each columns of an array
print(sample_array)

0    1
1    2
2    3
3    4
4    5
dtype: int64


In [5]:
# 2-Python program to convert a Panda module Series to Python list and it's type.
"""
Description:
    Function is Used to convert a Panda module Series to Python list and it's type.
Parameter:
    Sample List
Return:
    None
"""
sample_array = pd.Series([1,2,3,4,5])
print(sample_array)
print(type(sample_array))
list = sample_array.tolist()        #- used to convert the data elements of an array into a list.
print(list)
print(type(list))

0    1
1    2
2    3
3    4
4    5
dtype: int64
<class 'pandas.core.series.Series'>
[1, 2, 3, 4, 5]
<class 'list'>


In [6]:
# 3-Python program to add, subtract, multiple and divide two Pandas Series
"""
Description:
    Function is Used to add, subtract, multiple and divide two Pandas Series.
Parameter:
    Sample Series
Return:
    None
"""
seriesOne = pd.Series([1,2,3,4,5])
seriesTwo = pd.Series([6,7,8,9,10])
print("sum \n", seriesOne + seriesTwo)
print("sub \n", seriesOne - seriesTwo)
print("mul \n", seriesOne * seriesTwo)
print("div \n", seriesOne / seriesTwo)

sum 
 0     7
1     9
2    11
3    13
4    15
dtype: int64
sub 
 0   -5
1   -5
2   -5
3   -5
4   -5
dtype: int64
mul 
 0     6
1    14
2    24
3    36
4    50
dtype: int64
div 
 0    0.166667
1    0.285714
2    0.375000
3    0.444444
4    0.500000
dtype: float64


In [7]:
# 4-Python program to get the powers of an array values element-wise.
"""
Description:
    Function is Used to get the powers of an array values element-wise.
Parameter:
    Sample Series
Return:
    None
"""
my_array = np.arange(7)         #-Return evenly spaced values within a given interval.
print(np.power(my_array,3))     #-First array elements raised to powers from second array, element-wise.

[  0   1   8  27  64 125 216]


In [8]:
# 5-program to create and display a DataFrame from a specified dictionary data
#  which has the index labels
"""
Description:
    Function is Used to create and display a DataFrame from a specified dictionary data
    which has the index labels
Parameter:
    Sample Series
Return:
    None
"""
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael',
'Matthew', 'Laura', 'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

Data_Frame = pd.DataFrame(exam_data,index=labels) #-Two-dimensional, size-mutable, potentially heterogeneous tabular data.
print("Here is the Data Frame \n", Data_Frame)

Here is the Data Frame 
         name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes
d      James    NaN         3      no
e      Emily    9.0         2      no
f    Michael   20.0         3     yes
g    Matthew   14.5         1     yes
h      Laura    NaN         1      no
i      Kevin    8.0         2      no
j      Jonas   19.0         1     yes


In [9]:
# 6-program to display a summary of the basic information about a specified Data Frame and its data.
"""
Description:
    Function is Used to display a summary of the basic information about a specified Data Frame and its data
Parameter:
    Sample Series
Return:
    None
"""
Data_Frame = pd.DataFrame(exam_data,index=labels)
Data_Frame.info()           #-Print a concise summary of a DataFrame.

<class 'pandas.core.frame.DataFrame'>
Index: 10 entries, a to j
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   name      10 non-null     object 
 1   score     8 non-null      float64
 2   attempts  10 non-null     int64  
 3   qualify   10 non-null     object 
dtypes: float64(1), int64(1), object(2)
memory usage: 400.0+ bytes


In [10]:
# 7-Python program to get the first 3 rows of a given DataFrame. 
# Sample Python dictionary data and list labels:
"""
Description:
    Function is Used to to get the first 3 rows of a given DataFrame. 
    Sample Python dictionary data and list labels:
Parameter:
    Sample Series
Return:
    None
"""
result = Data_Frame.head(3)     #-Return the first n rows
print("Required Data Frame is: \n", result)

Required Data Frame is: 
         name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes


In [11]:
# 8-Python program to select the 'name' and 'score' columns from the following DataFrame
"""
Description:
    Function is Used to select the 'name' and 'score' columns from the following DataFrame.
Parameter:
    Sample Series
Return:
    None
"""
result = Data_Frame[['name','score']]
print("Required Data Frame is: \n ", result)

Required Data Frame is: 
          name  score
a  Anastasia   12.5
b       Dima    9.0
c  Katherine   16.5
d      James    NaN
e      Emily    9.0
f    Michael   20.0
g    Matthew   14.5
h      Laura    NaN
i      Kevin    8.0
j      Jonas   19.0


In [12]:
# 9-Python program to select the specified columns and rows from a given data frame.
"""
Description:
    Function is Used to select the specified columns and rows from a given data frame.
Parameter:
    Sample Series
Return:
    None
"""
result = Data_Frame.iloc[[1,3,5,6]][['name','score']]  #-Purely integer-location based indexing for selection by position.
print("Required Data Frame is:\n ", result)

Required Data Frame is:
        name  score
b     Dima    9.0
d    James    NaN
f  Michael   20.0
g  Matthew   14.5


In [13]:
# 10-Python program to select the rows where the number of attempts
#  in the examination is greater than 2
"""
Description:
    Function is Used to select the rows where the number of attempts
    in the examination is greater than 2
Parameter:
    Sample Series
Return:
    None
"""
attempts = Data_Frame['attempts']>2
result = Data_Frame[attempts]
print("Required Data Frame is:\n ", result)

Required Data Frame is:
        name  score  attempts qualify
b     Dima    9.0         3      no
d    James    NaN         3      no
f  Michael   20.0         3     yes


In [14]:
# 11-Python program to count the number of rows and columns of a DataFrame. Sample data
"""
Description:
    Function is Used to count the number of rows and columns of a DataFrame. Sample data
Parameter:
    Sample Series
Return:
    None
"""    
print("number of columns " ,Data_Frame.columns.__len__()) #Return the length of index
print("number of rows " ,Data_Frame.index.__len__())

number of columns  4
number of rows  10


In [15]:
# 12-Python program to select the rows where the score is missing
"""
Description:
    Function is Used to select the rows where the score is missing
Parameter:
    Sample Series
Return:
    None
"""
result = Data_Frame[Data_Frame['score'].isnull()] #-this function return dataframe of Boolean values which are True for NaN values.
print("Required Data Frame is:\n ", result)

Required Data Frame is:
      name  score  attempts qualify
d  James    NaN         3      no
h  Laura    NaN         1      no


In [16]:
# 13-Python program to select the rows where number of attempts in the examination is less
#  than 2 and score greater than 15
"""
Description:
    Function is Used to select the rows where number of attempts in the examination is less
    than 2 and score greater than 15
Parameter:
    Sample Series
Return:
    None
"""
result = Data_Frame[(Data_Frame['attempts']<2) & (Data_Frame['score']>15)]
print("Required Data Frame is: \n ", result)

Required Data Frame is: 
      name  score  attempts qualify
j  Jonas   19.0         1     yes


In [17]:
# 14-Python program to change the score in row 'd' to 11.5
"""
Description:
    Function is Used to change the score in row 'd' to 11.5
Parameter:
    Sample Series
Return:
    None
"""
Data_Frame.loc['d','score'] = 11.5  #-Access a group of rows and columns by label(s) or a boolean array.
print("Required Data Frame is:\n ", Data_Frame)

Required Data Frame is:
          name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes
d      James   11.5         3      no
e      Emily    9.0         2      no
f    Michael   20.0         3     yes
g    Matthew   14.5         1     yes
h      Laura    NaN         1      no
i      Kevin    8.0         2      no
j      Jonas   19.0         1     yes


In [18]:
# 15-Python program to calculate the sum of the examination attempts by the students
"""
Description:
    Function is Used to calculate the sum of the examination attempts by the students
Parameter:
    Sample Series
Return:
    None
"""
sum(Data_Frame['attempts'])

19

In [19]:
# 16-Program to calculate the mean score for each different student in DataFrame
"""
Description:
    Function is Used to calculate the mean score for each different student in DataFrame
Parameter:
    Sample Series
Return:
    None
"""
Data_Frame['score'].mean() #-Return the mean of the values over the requested axis.

13.333333333333334

In [20]:
# 17-Program to append a new row 'k' to data frame with given values for each column
"""
Description:
    Function is Used to append a new row 'k' to data frame with given values for each column
Parameter:
    Sample Series
Return:
    None
"""
new_row = {'name' : 'Suresh', 'score': 15.5, 'attempts': 1, 'qualify': "yes"}
Data_Frame.loc['k'] = new_row
print('appended : \n',Data_Frame)
Data_Frame = Data_Frame.drop('k')
print('original : \n',Data_Frame)

appended : 
         name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes
d      James   11.5         3      no
e      Emily    9.0         2      no
f    Michael   20.0         3     yes
g    Matthew   14.5         1     yes
h      Laura    NaN         1      no
i      Kevin    8.0         2      no
j      Jonas   19.0         1     yes
k     Suresh   15.5         1     yes
original : 
         name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes
d      James   11.5         3      no
e      Emily    9.0         2      no
f    Michael   20.0         3     yes
g    Matthew   14.5         1     yes
h      Laura    NaN         1      no
i      Kevin    8.0         2      no
j      Jonas   19.0         1     yes


In [21]:
# 18-program to sort the DataFrame first by 'name' in descending order,
# then by 'score' in ascending order.
"""
Description:
    Function is Used to sort the DataFrame first by 'name' in descending order,
    then by 'score' in ascending order.
Parameter:
    Sample Series
Return:
    None
"""
updated_data = Data_Frame.sort_values(['name'])
updated_data = Data_Frame.sort_values(['score'],ascending=False)
updated_data

name  score  attempts qualify
f    Michael   20.0         3     yes
j      Jonas   19.0         1     yes
c  Katherine   16.5         2     yes
g    Matthew   14.5         1     yes
a  Anastasia   12.5         1     yes
d      James   11.5         3      no
b       Dima    9.0         3      no
e      Emily    9.0         2      no
i      Kevin    8.0         2      no
h      Laura    NaN         1      no

In [22]:
# 19-program to replace the 'qualify' column contains the values 'yes' and 'no' with True and False
"""
Description:
    Function is Used to sort the DataFrame first by 'name' in descending order,
    then by 'score' in ascending order.
Parameter:
    Sample Series
Return:
    None
"""
new_frame = Data_Frame.copy() #-Make a copy of this object's indices and data.
new_frame['qualify'] = Data_Frame['qualify'].map({'yes':True,'no':False}) #-Map values of Series according to input correspondence.
new_frame


name  score  attempts  qualify
a  Anastasia   12.5         1     True
b       Dima    9.0         3    False
c  Katherine   16.5         2     True
d      James   11.5         3    False
e      Emily    9.0         2    False
f    Michael   20.0         3     True
g    Matthew   14.5         1     True
h      Laura    NaN         1    False
i      Kevin    8.0         2    False
j      Jonas   19.0         1     True

In [23]:
# 20-program to delete the 'attempts' column from the DataFrame
"""
Description:
    Function is Used to delete the 'attempts' column from the DataFrame.
Parameter:
    Sample Series
Return:
    None
"""
Data_Frame.drop('attempts',axis=1) #-Drop specified labels from rows or columns.

name  score qualify
a  Anastasia   12.5     yes
b       Dima    9.0      no
c  Katherine   16.5     yes
d      James   11.5      no
e      Emily    9.0      no
f    Michael   20.0     yes
g    Matthew   14.5     yes
h      Laura    NaN      no
i      Kevin    8.0      no
j      Jonas   19.0     yes

In [24]:
# 21-Program to insert a new column in existing DataFrame
"""
Description:
    Function is Used to insert a new column in existing DataFrame.
Parameter:
    Sample Series
Return:
    None
"""
roll_no = [1,2,3,4,5,6,7,8,9,10]
Data_Frame['Roll no.'] = roll_no
Data_Frame

name  score  attempts qualify  Roll no.
a  Anastasia   12.5         1     yes         1
b       Dima    9.0         3      no         2
c  Katherine   16.5         2     yes         3
d      James   11.5         3      no         4
e      Emily    9.0         2      no         5
f    Michael   20.0         3     yes         6
g    Matthew   14.5         1     yes         7
h      Laura    NaN         1      no         8
i      Kevin    8.0         2      no         9
j      Jonas   19.0         1     yes        10

In [25]:
# 22- Python program to iterate over rows in a DataFrame
"""
Description:
    Function is Used to iterate over rows in a DataFrame.
Parameter:
    Sample Series
Return:
    None
"""
for i in Data_Frame.index:
    print(Data_Frame['name'][i])

Anastasia
Dima
Katherine
James
Emily
Michael
Matthew
Laura
Kevin
Jonas


In [26]:
# 23-Python program to get list from DataFrame column headers
"""
Description:
    Function is Used to get list from DataFrame column headers.
Parameter:
    Sample Series
Return:
    None
"""
list_column_headers = Data_Frame.columns.tolist()
print(list_column_headers)

['name', 'score', 'attempts', 'qualify', 'Roll no.']


In [91]:
arr = np.array([[[2,2,4],[3,2,7]], [[2,2,3],[3,6,7]]])
print(arr[0:1])

[[[2 2 4]
  [3 2 7]]]


In [96]:
array = np.array([1,2,3,4,5])
array

array([1, 2, 3, 4, 5])

In [97]:
array[0] = 6

In [98]:
array


array([6, 2, 3, 4, 5])