In [2]:
import numpy as np
"""
@Author: Gyanendra
@Date: 18/01/2021 
@Last Modified by: Gyanendra
@Last Modified time: 18/01/2021 
@Title : Numpy Python Problems
"""

'\n@Author: Gyanendra\n@Date: 18/01/2021 \n@Last Modified by: Gyanendra\n@Last Modified time: 18/01/2021 \n@Title : Numpy Python Problems\n'

In [2]:
# 1-Python program to convert a list of numeric value into a one-dimensional Numpy Array
"""
Description:
    Function is Used for convert a list of numeric value into a one-dimensional Numpy Array
Parameter:
    Sample List
Return:
    None
"""
sample_list = [12.23, 13.32, 100, 36.32]
numpy_array = np.array(sample_list)
print(numpy_array)

[ 12.23  13.32 100.    36.32]


In [3]:
# 2-Program of 3x3 matrix with values ranging from 2 to 10.
"""
Description:
    Function is Used for 3x3 matrix with values ranging from 2 to 10.
Parameter:
    Dimension Size
Return:
    Three Dimension
"""
three_dimension = np.reshape(np.arange(2,11),(3,3))
print(three_dimension)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


In [4]:
# 3-Python program to create a null vector of size 10 and update sixth value to 11.
"""
Description:
    Function is Used for create a null vector of size 10 and update sixth value to 11.
Parameter:
    None
Return:
    None
"""
zero_array = np.zeros(10)
zero_array[6] = 11
print(zero_array)

[ 0.  0.  0.  0.  0.  0. 11.  0.  0.  0.]


In [5]:
# 4-Python program to reverse an array (first element becomes last).
"""
Description:
    Function is Used for reverse an array
Parameter:
    Sample List
Return:
    First Element becomes last
"""
sample_list = [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37]
numpy_array = np.array(sample_list)
reversed_array = numpy_array[::-1]
print(reversed_array)

[37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14
 13 12]


In [6]:
# 5-Python program to create a 2d array with 1 on the border and 0 inside.
"""
Description:
    Function is Used for create a 2d array with 1 on the border and 0 inside
Parameter:
    Sample Array
Return:
    None
"""
one_array = np.ones(25)
new_one_array = one_array.reshape(5,5)
new_one_array[1:4,1:4]=0
print(new_one_array)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [7]:
# 6-Python program to add a border (filled with 0's) around an existing array.
"""
Description:
    Function is Used to add a border (filled with 0's) around an existing array
Parameter:
    Sample Array
Return:
    Required Array
"""
one_arr = np.ones((3,3))
one_arr = np.pad(one_arr, pad_width=1, mode='constant', constant_values=0)
print(one_arr)

[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


In [8]:
# 7-Python program to create a 8eight_array8 matrieight_array and fill it with a checkerboard pattern.
"""
Description:
    Function is Used to create a 8eight_array8 matrieight_array and fill it with a checkerboard pattern.
Parameter:
    Sample Array
Return:
    Required Array
"""
eight_array = np.zeros((8,8))
eight_array[1::2,::2] = 1
eight_array[::2,1::2] = 1
print(eight_array)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


In [9]:
# 8-Python program to convert a list and tuple into arrays.
"""
Description:
    Function is Used to convert a list and tuple into arrays.
Parameter:
    Sample List and Sample Tuple
Return:
    Required Array's
"""
sample_list = [1,2,3,4,5,6,7,8]
sample_list = np.array(sample_list)
print(sample_list)

sample_tuple = (1,2,3,4)
print(np.array(sample_tuple))

[1 2 3 4 5 6 7 8]
[1 2 3 4]


In [10]:
# 9-Python program to append values to the end of an array.
"""
Description:
    Function is Used to append values to the end of an array.
Parameter:
    Sample Array
Return:
    Required Array
"""
appended_array = np.array([10, 20, 30])
np.append(appended_array, (40,50,60,70,80,90))


array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [11]:
# 10-a Python program to find the real and imaginary parts of an array of complex numbers.
"""
Description:
    Function is Used to find the real and imaginary parts of an array of complex numbers.
Parameter:
    Sample Array
Return:
    Required Array
"""
equat = np.array([ 1.00000000+0.j,0.70710678+0.70710678j])
real = np.array([])
imaginary = np.array([])

print("Real Part of Equ.", equat.real)
print("Imaginary Part of Equ.", equat.imag)

Real Part of Equ. [1.         0.70710678]
Imaginary Part of Equ. [0.         0.70710678]


In [12]:
# 11-Python program to find the number of elements of an array, length of one 
# array element in bytes and total bytes consumed by the elements.
"""
Description:
    Function is Used to find the the number of elements of an array, length of one 
    array element in bytes and total bytes consumed by the elements.
Parameter:
    Sample Array
Return:
    Required Size
"""
number = np.array([1,2,3,4,5,6,100])
print("Items of an array: ", number.size)
print("Length of one array element in bytes: ", number.itemsize)
print("Total bytes consumed by the elements: ", number.nbytes)

Items of an array:  7
Length of one array element in bytes:  4
Total bytes consumed by the elements:  28


In [13]:
# 12-Python program to find common values between two arrays. 
"""
Description:
    Function is Used to find to find common values between two arrays.
Parameter:
    Sample Array
Return:
    Required Array
"""
array_one= np.array([0, 10, 20, 40, 60])
array_two= np.array([10, 30, 40])

print(np.intersect1d(array_one,array_two))

[10 40]


In [14]:
# 13-Write a Python program to find the set difference of two arrays. The set difference
# will return the sorted, unique values in array1 that are not in array2.
"""
Description:
    Function is Used to find to find find the set difference of two arrays.
Parameter:
    Sample Array
Return:
    Required Array
"""
array_one= np.array([ 0, 10, 20, 40, 60, 80])
array_two= np.array([10, 30, 40, 50, 70, 90])
print(np.setdiff1d(array_one,array_two))

[ 0 20 60 80]


In [15]:
# 14-Python program to find the set exclusive-or of two arrays. Set exclusive-or
# will return the sorted, unique values that are in only one (not both) of the input arrays.
"""
Description:
    Function is Used to the set exclusive-or of two arrays.
Parameter:
    Sample Array
Return:
    Required Array
"""
array_one= np.array([ 0, 10, 20, 40, 60, 80])
array_two= np.array([10, 30, 40, 50, 70])

print(np.setxor1d(array_one,array_two))

[ 0 20 30 50 60 70 80]


In [3]:
# 15-Python program compare two arrays using numpy.
"""
Description:
    Function is Used to compare two arrays using numpy.
Parameter:
    Sample Array
Return:
    Required Array
"""
array_one = np.array([1, 2])
array_two = np.array([4, 5])

print(np.greater(array_one, array_two))
print(np.greater_equal(array_one, array_two))
print(np.less(array_one, array_two))
print(np.less_equal(array_one, array_two))

[False False]
[False False]
[ True  True]
[ True  True]


In [4]:
# 16-Python program to create a contiguous flattened array.
"""
Description:
    Function is Used to a contiguous flattened array.
Parameter:
    Sample Array
Return:
    Required Array
"""
array_one = np.array([[10, 20, 30], [20, 40, 50]])
converted_array = np.ravel(array_one)
print(converted_array)

[10 20 30 20 40 50]


In [6]:
# 17-Python program to change the data type of an array.
"""
Description:
    Function is Used to change the data type of an array.
Parameter:
    Sample Array
Return:
    Required Array
"""
my_array= np.array([ 0, 10, 20, 40, 60, 80])
print(my_array.dtype)
created_array = my_array.astype(float)
print(created_array.dtype)

int32
float64


In [7]:
# 18-Python program to create a 3-D array with ones on a diagonal and zeros elsewhere.
"""
Description:
    Function is Used to create a 3-D array with ones on a diagonal and zeros elsewhere.
Parameter:
    Sample Array
Return:
    Required Array
"""
array = np.eye(3)
print(array)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [13]:
# 19-Python program to create an array which looks like below array.
"""
Description:
    Function is Used to create an array which looks like below array.
Parameter:
    Sample Array
Return:
    Required Array
"""
array = np.tri(3, 3,2)
print(array)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [18]:
# 20-Python program to concatenate two 2-dimensional arrays.
"""
Description:
    Function is Used to concatenate two 2-dimensional arrays.
Parameter:
    Sample Array
Return:
    Required Array
"""
array_one = np.array([[0, 1, 3], [5, 7, 9]])
array_two = np.array([[0, 2, 4], [6, 8, 10]])
array_three = np.concatenate((array_one, array_two), 1)
print(array_three)

[[ 0  1  3  0  2  4]
 [ 5  7  9  6  8 10]]


In [21]:
# 21-program to make an array immutable (read-only).
"""
Description:
    Function is Used to make an array immutable (read-only)
Parameter:
    Sample Array
Return:
    Required Array
"""
array_zero = np.zeros(10)
array_zero.flags.writeable = False
# array_zero[0] = 1

In [22]:
# 22-Python program to create an array of (3, 4) shape, multiply every element
# value by 3 and display the new array.
"""
Description:
    Function is Used to to create an array of (3, 4) shape, multiply every element
    value by 3 and display the new array.
Parameter:
    Sample Array
Return:
    Required Array
"""
array = np.array([[1,2,3,4],[5,6,7,8],[1,2,3,4]])
print(array*3)

[[ 3  6  9 12]
 [15 18 21 24]
 [ 3  6  9 12]]


In [23]:
# 23-program to convert a NumPy array into Python list structure.
"""
Description:
    Function is Used to convert a NumPy array into Python list structure
Parameter:
    Sample Array
Return:
    Required Array
"""
array = np.arange(10)
print(type(array))
new_arr = array.tolist()
print(type(new_arr))

<class 'numpy.ndarray'>
<class 'list'>


In [24]:
# 24-Python program to convert a NumPy array into Python list structure.
"""
Description:
    Function is Used to convert a NumPy array into Python list structure
Parameter:
    Sample Array
Return:
    Required Array
"""
sample_array = np.array([ 0.26153123, 0.52760141, 0.5718299, 0.5927067, 0.7831874, 0.69746349,0.35399976, 0.99469633, 0.0694458, 0.54711478])
np.set_printoptions(precision=3)
print(sample_array)

[0.262 0.528 0.572 0.593 0.783 0.697 0.354 0.995 0.069 0.547]


In [26]:
# 25-Python program to suppresses the use of scientific notation for small
# numbers in numpy array.
"""
Description:
    Function is Used to suppresses the use of scientific notation for small
    numbers in numpy array
Parameter:
    Sample Array
Return:
    Required Array
"""
sample_array = np.array([ 1.60000000e-10, 1.60000000e+00, 1.20000000e+03, 2.35000000e-01])
np.set_printoptions(precision=2, suppress=True)
print(sample_array)

[   0.      1.6  1200.      0.23]


In [25]:
# 26-Python program to how to add an extra column to an numpy array.
"""
Description:
    Function is Used to add an extra column to an numpy array.
Parameter:
    Sample Array
Return:
    Required Array
"""
sample_array = np.array([[ 10, 20, 30],[ 40, 50, 60]])
resulted_array = np.array([[100],[200]])

print(np.append(sample_array,resulted_array,axis=1))

[[ 10  20  30 100]
 [ 40  50  60 200]]


In [28]:
# 27-Python program to remove specific elements in a numpy array
"""
Description:
    Function is Used to remove specific elements in a numpy array
Parameter:
    Sample Array
Return:
    Required Array
"""
sample_array = np.array([1,2,3,4,5,6,7,8,9])
resulted_array = np.delete(sample_array,[3,1,5])
print('Here is the Updated Array: ', resulted_array)


Here is the Updated Array:  [1 3 5 7 8 9]
